# Tên ?ng d?ng
spring.application.name=pbl5

# ==========================================
# C?U HÌNH K?T N?I MYSQL
# ==========================================
# 1. URL: T? ??ng t?o database 'pbl5' n?u ch?a có (createDatabaseIfNotExist=true)
spring.datasource.url=jdbc:mysql://localhost:3306/pbl5?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC

# 2. Tài kho?n & M?t kh?u (Hãy thay '12345678' b?ng m?t kh?u MySQL th?t trên máy b?n)
spring.datasource.username=root
spring.datasource.password=

# 3. Driver k?t n?i
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ==========================================
# C?U HÌNH JPA / HIBERNATE
# ==========================================
# T? ??ng t?o/c?p nh?t c?u trúc b?ng t? code Java (Entity) vào Database
spring.jpa.hibernate.ddl-auto=update

# Hi?n th? các câu l?nh SQL mà Spring th?c hi?n d??i console ?? d? debug
spring.jpa.show-sql=true

# ??nh d?ng câu l?nh SQL cho d? ??c
spring.jpa.properties.hibernate.format_sql=true

# Dialect giúp Hibernate t?i ?u hóa câu l?nh SQL cho MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# ==========================================
# C?U HÌNH KHÁC (Tùy ch?n)
# ==========================================
# C?ng ch?y ?ng d?ng (M?c ??nh là 8080)
server.port=8080
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tamke228@gmail.com
spring.mail.password=cuzqoivraazeeedz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true